version: 2.1
orbs:
  go: circleci/go@2.1.0
  node: circleci/node@5.2.0
  slack: circleci/slack@4.10.1
  gcp-cli: circleci/gcp-cli@3.0.1
  python: circleci/python@1.1.0
  utils: ethereum-optimism/circleci-utils@0.0.4

parameters:
  chain:
    type: string
    default: "__required__"

jobs:
  upload-chain-artifacts:
    machine:
      image: ubuntu-2004:current
    steps:
      - run:
          name: Verify Chain Parameter
          command: |
            if [ "<< pipeline.parameters.chain>>" = "__required__" ]; then
              echo "Error: The 'chain' parameter is required but was not provided, skipping upload"
              exit 1
            fi
            echo "export CHAIN=<< pipeline.parameters.chain>>" >> $BASH_ENV
      - checkout
      - utils/gcp-oidc-authenticate
      - run:
          name: Get Current Commit Hash
          command: echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $BASH_ENV
      - run:
          name: Generate Genesis File
          working_directory: validation
          command: |
            go run generate-genesis/main.go $COMMIT_HASH
      - run:
          name: Generate Rollup Config
          working_directory: validation
          command: |
            go run generate-rollup-config/main.go $COMMIT_HASH
      - gcp-cli/install
      - run:
          name: Upload Artifacts
          working_directory: validation
          command: |
            FOLDER="chains"

            gsutil cp ./generate-genesis/output-${COMMIT_HASH}/${CHAIN}.json \
              gs://${GCS_BUCKET}/${FOLDER}/${CHAIN}/genesis.json
            gsutil cp ./generate-rollup-config/output-${COMMIT_HASH}/${CHAIN}.json \
              gs://${GCS_BUCKET}/${FOLDER}/${CHAIN}/rollup.json

            # Upload with commit hash for historical records
            gsutil cp ./generate-genesis/output-${COMMIT_HASH}/${CHAIN}.json \
              gs://${GCS_BUCKET}/${FOLDER}/${CHAIN}/${COMMIT_HASH}/genesis.json
            gsutil cp ./generate-rollup-config/output-${COMMIT_HASH}/${CHAIN}.json \
              gs://${GCS_BUCKET}/${FOLDER}/${CHAIN}/${COMMIT_HASH}/rollup.json

workflows:
  upload-chain-artifacts-workflow:
    when:
      not:
        equal: ["__required__", << pipeline.parameters.chain>>]
    jobs:
      - upload-chain-artifacts:
          context: oplabs-artifacts
