# Standard Chain Config Parameters
[resource_config]
max_resource_limit = 20000000
elasticity_multiplier = 10
base_fee_max_change_denominator = 8
minimum_base_fee = 1000000000
system_tx_max_gas = 1000000
maximum_base_fee = "340_282_366_920_938_463_463_374_607_431_768_211_455"

[l2_output_oracle]
submission_interval = [1, 86400]
l2_block_time = [2, 2]
challenge_period_seconds = [12, 12] # i.e. finalization period

[gas_price_oracle.pre-ecotone]
decimals = [6, 6]
overhead = [188, 2_100]
scalar = [684_000, 1_000_000]

[gas_price_oracle.ecotone]
decimals = [6, 6]
blob_base_fee_scalar = [0, 10_000_000]
base_fee_scalar = [0, 10_000_000]

[system_config]
gas_limit = [1000, 60_000_000]

# Standard Chain Config Roles
[[l1.universal]]
name = "AddressManager"
method = "owner()"
resolves_to_address_of = "ProxyAdmin"

[[l1.universal]]
name = "SystemConfigProxy"
method = "owner()"
resolves_to_address_of = "SystemConfigOwner"

[[l1.universal]]
name = "ProxyAdmin"
method = "owner()"
resolves_to = "0x5a0Aae59D09fccBdDb6C6CcEB07B7279367C3d2A"
resolves_to_address_of = "ProxyAdminOwner"

[[l1.universal]]
name = "L1CrossDomainMessengerProxy"
method = "PORTAL()"
resolves_to_address_of = "OptimismPortalProxy"

[[l1.universal]]
name = "L1ERC721BridgeProxy"
method = "admin()"
resolves_to_address_of = "ProxyAdmin"

[[l1.universal]]
name = "L1ERC721BridgeProxy"
method = "messenger()"
resolves_to_address_of = "L1CrossDomainMessengerProxy"

[[l1.universal]]
name = "L1StandardBridgeProxy"
method = "getOwner()"
resolves_to_address_of = "ProxyAdmin"

[[l1.universal]]
name = "L1StandardBridgeProxy"
method = "messenger()"
resolves_to_address_of = "L1CrossDomainMessengerProxy"

[[l1.universal]]
name = "OptimismMintableERC20FactoryProxy"
method = "admin()"
resolves_to_address_of = "ProxyAdmin"

[[l1.universal]]
name = "OptimismMintableERC20FactoryProxy"
method = "BRIDGE()"
resolves_to_address_of = "L1StandardBridgeProxy"

[[l1.universal]]
name = "OptimismPortalProxy"
method = "admin()"
resolves_to_address_of = "ProxyAdmin"

[[l1.universal]]
name = "ProxyAdmin"
method = "owner()"
resolves_to_address_of = "ProxyAdminOwner"

[[l1.universal]]
name = "ProxyAdmin"
method = "addressManager()"
resolves_to_address_of = "AddressManager"

[[l1.universal]]
name = "SystemConfigProxy"
method = "admin()"
resolves_to_address_of = "ProxyAdmin"

[[l1.universal]]
name = "SystemConfigProxy"
method = "owner()"
resolves_to_address_of = "SystemConfigOwner"

[[l1.nonFPAC]]
name = "OptimismPortalProxy"
method = "GUARDIAN()"
resolves_to_address_of = "Guardian"

[[l1.nonFPAC]]
name = "OptimismPortalProxy"
method = "SYSTEM_CONFIG()"
resolves_to_address_of = "SystemConfigProxy"

[[l1.nonFPAC]]
name = "OptimismPortalProxy"
method = "L2_ORACLE()"
resolves_to_address_of = "L2OutputOracleProxy"

[[l1.nonFPAC]]
name = "L2OutputOracleProxy"
method = "admin()"
resolves_to_address_of = "ProxyAdmin"

[[l1.nonFPAC]]
name = "L2OutputOracleProxy"
meethod = "CHALLENGER()"
resolves_to_address_of = "Challenger"

[[l1.FPAC]]
name = "DisputeGameFactoryProxy"
method = "admin()"
resolves_to_address_of = "ProxyAdmin"

[[l1.FPAC]]
name = "DisputeGameFactoryProxy"
method = "owner()"
resolves_to_address_of = "ProxyAdminOwner"

[[l1.FPAC]]
name = "AnchorStateRegistryProxy"
method = "admin()"
resolves_to_address_of = "ProxyAdmin"

[[l1.FPAC]]
name = "DelayedWETHProxy"
method = "admin()"
resolves_to_address_of = "ProxyAdmin"

[[l1.FPAC]]
name = "OptimismPortalProxy"
method = "guardian()"
resolves_to_address_of = "Guardian"

[[l1.FPAC]]
name = "OptimismPortalProxy"
method = "systemConfig()"
resolves_to_address_of = "SystemConfigProxy"
