op_contracts_release = "op-contracts/v1.4.0"

[contract_tag]

# Fault Proofs https://github.com/ethereum-optimism/optimism/releases/tag/op-contracts%2Fv1.4.0
[contract_tag."op-contracts/v1.4.0"]
address_manager = { version = "" }
l1_cross_domain_messenger = { version = "2.3.0" }
l1_erc721_bridge = { version = "2.1.0" }
l1_standard_bridge = { version = "2.1.0" }
optimism_mintable_erc20_factory = { version = "1.9.0" }
optimism_portal = { version = "3.10.0" }
system_config = { version = "2.2.0" }
protocol_versions = { version = "1.0.0" }
anchor_state_registry = { version = "1.0.0" }
delayed_weth = { version = "1.0.0" }
dispute_game_factory = { version = "1.0.0" }
fault_dispute_game = { version = "1.2.0" }
permissioned_dispute_game = { version = "1.2.0" }
mips = { version = "1.0.1" }
preimage_oracle = { version = "1.0.0" }

# Fault Proofs https://github.com/ethereum-optimism/optimism/releases/tag/op-contracts%2Fv1.3.0
[contract_tag."op-contracts/v1.3.0"]
address_manager = { version = "1.0.0", address = "0xdE1FCfB0851916CA5101820A69b13a4E276bd81F" }
l1_cross_domain_messenger = { version = "2.3.0", address = "0xD3494713A5cfaD3F5359379DfA074E2Ac8C6Fd65" }
l1_erc721_bridge = { version = "2.1.0", address = "0xAE2AF01232a6c4a4d3012C5eC5b1b35059caF10d" }
l1_standard_bridge = { version = "2.1.0", address = "0x64B5a5Ed26DCb17370Ff4d33a8D503f0fbD06CfF" }
l2_output_oracle = { version = "1.8.0", address = "0xF243BEd163251380e78068d317ae10f26042B292" }
optimism_mintable_erc20_factory = { version = "1.9.0", address = "0xE01efbeb1089D1d1dB9c6c8b135C934C0734c846" }
optimism_portal = { version = "2.5.0", address = "0x2D778797049FE9259d947D1ED8e5442226dFB589" }
system_config = { version = "1.12.0", address = "0xba2492e52F45651B60B8B38d4Ea5E2390C64Ffb1" }
protocol_versions = { version = "1.0.0" }
anchor_state_registry = { version = "1.0.0" }
delayed_weth = { version = "1.0.0" }
dispute_game_factory = { version = "1.0.0" }
fault_dispute_game = { version = "1.2.0" }
permissioned_dispute_game = { version = "1.2.0" }
