name = "OPCM Sepolia Test deployment"
chain_id = 111222333444555666
superchain_level = 0
standard_chain_candidate = true       # This is a temporary field which causes most of the standard validation checks to run on this chain

[addresses]
AddressManager = ""
AnchorStateRegistryProxy = ""
BatchSubmitter = ""
Challenger = ""
DelayedWETHProxy = ""                  # Permissioned game WETH proxy.
DisputeGameFactoryProxy = ""
FaultDisputeGame = ""
Guardian = ""
L1CrossDomainMessengerProxy = ""
L1ERC721BridgeProxy = ""
L1StandardBridgeProxy = ""
MIPS = ""
OptimismMintableERC20FactoryProxy = ""
OptimismPortalProxy = ""
PermissionedDisputeGame = ""
PreimageOracle = ""
Proposer = ""
ProxyAdmin = ""
ProxyAdminOwner = ""
SystemConfigOwner = ""
SystemConfigProxy = ""
UnsafeBlockSigner = ""
